# Generated by Django 5.0.3 on 2024-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('r1', models.CharField(max_length=7)),
                ('hname', models.CharField(max_length=30)),
                ('per', models.IntegerField()),
                ('hsname', models.CharField(max_length=30)),
                ('percent', models.IntegerField()),
                ('gname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=10)),
                ('percentage', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=10)),
                ('per2', models.IntegerField()),
                ('anum', models.IntegerField()),
                ('pnum', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
