# Generated by Django 5.0.3 on 2024-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=10)),
                ('cou', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=10)),
            ],
        ),
    ]
