# Generated by Django 5.0.3 on 2024-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_addsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff1', models.CharField(max_length=30)),
                ('leave', models.DateField()),
                ('eleave', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
