# Generated by Django 5.0.3 on 2024-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_staffleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stafffeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
    ]
