# Generated by Django 5.0.3 on 2024-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_stafffeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('msgg', models.CharField(max_length=50)),
            ],
        ),
    ]
