# Generated by Django 5.0.3 on 2024-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='replystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=40)),
            ],
        ),
    ]
