# Generated by Django 5.0.3 on 2024-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_replystaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student1', models.CharField(max_length=30)),
                ('leave', models.DateField()),
                ('eleave', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
