# Generated by Django 5.0.3 on 2024-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_studentleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replystudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=40)),
            ],
        ),
    ]
